package order

const (
	idCol = "id"

	deliveryTableName = "delivery"
	delNameCol        = "name"
	phoneCol          = "phone"
	zipCol            = "zip"
	cityCol           = "city"
	addressCol        = "address"
	regionCol         = "region"
	emailCol          = "email"

	paymentTableName = "payment"
	transactionCol   = "transaction"
	requestIDCol     = "request_id"
	currencyCol      = "currency"
	providerCol      = "provider"
	amountCol        = "amount"
	paymentDtCol     = "payment_dt"
	bankCol          = "bank"
	deliveryCostCol  = "delivery_cost"
	goodsTotalCol    = "goods_total"
	customFeeCol     = "custom_fee"

	itemTableName       = "item"
	chrtIDCol           = "chrt_id"
	itemsTrackNumberCol = "track_number"
	priceCol            = "price"
	ridCol              = "rid"
	itemNameCol         = "name"
	saleCol             = "sale"
	sizeCol             = "size"
	totalPriceCol       = "total_price"
	nmIDCol             = "nm_id"
	brandCol            = "brand"
	statusCol           = "status"

	ordersTableName      = "orders"
	orderUIDCol          = "order_uid"
	ordersTrackNumberCol = "track_number"
	entryCol             = "entry"
	deliveryIdCol        = "delivery_id"
	paymentIdCol         = "payment_id"
	localeCol            = "locale"
	internalSignatureCol = "internal_signature"
	customerIDCol        = "customer_id"
	deliveryServiceCol   = "delivery_service"
	shardkeyCol          = "shardkey"
	smIDCol              = "sm_id"
	dateCreatedCol       = "date_created"
	oofShardCol          = "oof_shard"

	ordersAndItemsTableName = "orders_and_items"
	orderIdCol              = "order_id"
	itemIdCol               = "item_id"
)